---
title: Seagrass mapping in two mudflats in the Auray River
subtitle: About a rapid evolution of seagrasses
author:
  - name: Simon Oiry
    email: oirysimon@gmail.com
    orcid: 0000-0001-7161-5246
    affiliations: 
        - id: ISOMER
          name: Nantes Université, UR 2160, F-44000 Nantes, France
          department: Institut des Substances et Organismes de la Mer, ISOMer
          address: 2 chemin de la houssinière
          city: Nantes
          state: France
          postal-code: 44300
    attributes:
        corresponding: true
  - name: Bede Ffinian Rowe Davies
    email: bedeffinian@gmail.com
    orcid: 0000-0001-6462-4347
    affiliations: 
        - id: ISOMER
          name: Nantes Université, UR 2160, F-44000 Nantes, France
          department: Institut des Substances et Organismes de la Mer, ISOMer
          address: 2 chemin de la houssinière
          city: Nantes
          state: France
          postal-code: 44300
    attributes:
        corresponding: true
abstract: |
  Maps of seagrass in two sites in the Auray River. These two sites were studied by Maxime Daviray during his PhD. Seagrass appeared very quickly during his PhD. This work aims to describe this rapid evolution of seagrasses.
keywords: 
  - Remote Sensing
  - Sentinel-2
  - Seagrass
date: last-modified
bibliography: library.bib
number-sections: true
notebook-links: false
---

```{r library}
#| cache: false
#| echo: false
#| warning: false
#| eval: true

library(tidyverse)
library(terra)

```

The data and scripts used for this work can be found [here](https://github.com/SigOiry/Seagrass_maps_Maxime).

# Materials & Methods

## Seagrass mapping using Sentinel-2

To map the seagrass extent over time, the Sentinel-2 constellation has been used. Level-2 images, which are already orthorectified and atmospherically corrected using Sen2Cor, have been downloaded using the Copernicus Platform [@Copernicus_Sentinel]. One low tide, cloud-free image per year, nearest to the period of maximum seagrass biomass at this latitude, has been used. A total of 8 images have beed used (@tbl-tide-data).

| Acquisition Date (UTC) | Low Tide Time (UTC) | Time Difference with Low tide |
|:---------------------:|:------------------:|:---------------------------:|
|    2016-11-03 11:12    |       12 : 08       |          \+ 00 : 56           |
|    2017-10-04 11:08    |       09 : 09       |          \- 01 : 59           |
|    2018-09-29 11:08    |       12 : 43       |          \+ 01 : 35           |
|    2019-09-14 11:06    |       10 : 28       |          \+ 00 : 38           |
|    2020-08-04 11:06    |       10 : 45       |          \+ 00 : 21           |
|    2021-10-08 11:09    |       11 : 18       |          \- 00 : 09           |
|    2022-08-29 11:06    |       11 : 27       |          \- 00 : 21           |
|    2023-09-03 11:06    |       12 : 28       |          \- 01 : 22           |

: Acquisition dates of Sentinel-2 images used to map seagrass in the Auray River. Tide times were retrieved from the SHOM and correspond to the tides at the Locmariaquer tide gauge, situated approximately 2 km from the study sites. {#tbl-tide-data}

The *Intertidal Classification of Europe: Categorising Reflectance of Emerged Areas of Marine vegetation with Sentinel-2* model (ICE CREAMS, @Davies2024), a neural network classifier designed to identify and discriminate intertidal vegetation in Europe, has been applied to each Sentinel-2 image. Pixels of the Magnoliopsida class (seagrasses) have been isolated, and the Normalized Difference Vegetation Index (NDVI, @rouse1974monitoring), a commonly used remote sensing biomass proxy for vegetation, has been employed. The equation of @zoffoli2020sentinel have been used to transform NDVI values into Seagrass Percent Cover ([@eq-std]). SPC values below 20%, corresponding to low biomass pixel, with a high risk of confusion with other vegetation classes, have been remove from the rest of the analysis.

$$
SPC = 172.06 \times NDVI - 22.18
$$ {#eq-std}

Maps and analysis have then been performed using the *Terra* package of R, in a *Tidyverse* workflow [@hijmans2023terra ; @wickham2017easily]. 

# Results

## Evolution of the spatial distribution of seagrasses over time


